name: commitDevCode

on:
  workflow_call:
    inputs:
      api-name:
        type: string
        required: true
      api-version:
        type: string
        required: true
        

jobs:
  say-hello:
    name: sayHello
    runs-on: self-hosted
    steps:
      - name: Echo Inputs
        run: |
          echo "API Name: ${{ inputs.api-name }}"
          echo "API Version: ${{ inputs.api-version }}"