on:
  workflow_call:
    inputs:
      apiName:
        type: string
        description: API Name
        required: true
      apiVersion:
        type: string
        description: API Version
        required: true
    secrets:
      ghBotUsername:
        required: true
      ghBotEmail:
        required: true  
      ghBotPat:
        required: true    

env:
  APIM_ENVIRONMENT: dev
  WORK_DIR: /tmp/workflow-${{ github.run_id }}-${{ github.run_number }}

jobs:
  commit-new-version:
    name: commit new API version
    runs-on: self-hosted
    steps:
      - name: Create unique working directory
        run: |
          mkdir -p ${{ env.WORK_DIR }}
          cd ${{ env.WORK_DIR }}
          echo "Working in: $(pwd)"
      
      - name: Process API Parameters
        id: process-params
        run: |
          # Normalize API name (lowercase and trim)
          API_NAME_NORMALIZED=$(echo "${{ inputs.apiName }}" | tr '[:upper:]' '[:lower:]' | xargs)
          echo "api-name-normalized=$API_NAME_NORMALIZED" >> $GITHUB_OUTPUT
          
          # Extract major version (e.g., 1.0.0 -> v1)
          API_VERSION_MAJOR=$(echo "${{ inputs.apiVersion }}" | cut -d'.' -f1)
          API_VERSION_MAJOR="v$API_VERSION_MAJOR"
          echo "api-version-major=$API_VERSION_MAJOR" >> $GITHUB_OUTPUT
          
          # Echo results
          echo "Original API Name: ${{ inputs.apiName }}"
          echo "Normalized API Name: $API_NAME_NORMALIZED"
          echo "Original API Version: ${{ inputs.apiVersion }}"
          echo "Major Version: $API_VERSION_MAJOR"

      - name: Export API Data
        id: export-api
        run: |
          
          # Export API as ZIP using apictl (assuming apictl is pre-configured)
          apictl export api -n ${{ inputs.apiName }} -v ${{ inputs.apiVersion }} -e ${{ env.APIM_ENVIRONMENT }} 
          
          # Find the specific exported ZIP file for this API and version
          ZIP_FILE=$(find /home/ghrunner/.wso2apictl/exported/apis/${{ env.APIM_ENVIRONMENT }}/ -name "*${{ inputs.apiName }}*${{ inputs.apiVersion }}*.zip" -type f -newermt "5 minutes ago" | head -1)
          if [ -z "$ZIP_FILE" ]; then
            echo "Error: No ZIP file found after API export"
            exit 1
          fi
          echo "zip-file=$ZIP_FILE" >> $GITHUB_OUTPUT
          echo "Exported ZIP file: $ZIP_FILE"

      - name: Commit API ZIP to Repository
        run: |
          cd ${{ env.WORK_DIR }}
          
          # Clone the target repository
          git clone https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/${{ steps.process-params.outputs.api-name-normalized }}.git target-repo
          cd target-repo
          
          # Create directory structure if it doesn't exist
          if [ ! -d "apim/${{ steps.process-params.outputs.api-version-major }}/Conf" ]; then
            mkdir -p apim/${{ steps.process-params.outputs.api-version-major }}/Conf
          fi
          
          # Copy ZIP file to target location
          cp ${{ steps.export-api.outputs.zip-file }} apim/${{ steps.process-params.outputs.api-version-major }}/Conf/
          
          # Configure git
          git config user.name ${{ secrets.ghBotUsername }}
          git config user.email ${{ secrets.ghBotEmail }}
          
          # Add and commit changes
          git add .
          git commit -m "Add API configuration for ${{ inputs.apiName }} version ${{ inputs.apiVersion }}"
          
          # Push changes
          git push https://${{ secrets.ghBotUsername }}:${{ secrets.ghBotPat }}@github.com/${{ github.repository_owner }}/${{ steps.process-params.outputs.api-name-normalized }}.git main
          
      - name: Cleanup working directory
        if: always()
        run: |
          rm -rf ${{ env.WORK_DIR }}
          echo "Cleaned up working directory: ${{ env.WORK_DIR }}"