on:
  workflow_dispatch:
    inputs:
      apiName:
        type: string
        description: API Name
        required: true
      apiVersion:
        type: string
        description: API Version
        required: true
        

jobs:
  say-hello:
    name: sayHello
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: |
          echo "API Name: ${{ inputs.apiName }}"
          echo "API Version: ${{ inputs.apiVersion }}"